# Generated by Django 5.0.1 on 2024-01-24 03:57
from uuid import uuid4
from django.db import migrations, models
class Migration(migrations.Migration):
  initial = True
  dependencies = []
  operations = [
    migrations.CreateModel(
      name = 'Contact',
      options = {
        'verbose_name': 'Inquiry',
        'verbose_name_plural': 'Inquiries',
        'db_table': 'inquiries',
      },
      fields = [(
        'id',
        models.UUIDField(
          primary_key = True,
          default = uuid4,
          editable = False
        )
      ), (
        'listing',
        models.CharField()
      ), (
        'listing_id',
        models.IntegerField()
      ), (
        'first',
        models.CharField()
      ), (
        'last',
        models.CharField()
      ),  (
        'email',
        models.CharField()
      ), (
        'phone',
        models.CharField()
      ), (
        'message',
        models.TextField(
          blank = True
        )
      ), (
        'user_id',
        models.IntegerField(
          blank = True
        )
      ), (
        'created_at',
        models.DateTimeField(
          auto_now_add = True
        )
      ), (
        'updated_at',
        models.DateTimeField(
          auto_now = True
        )
      )]
    )
  ]