"""
Inquiry SQL table migration
Generated by Django 5.0.1 on 2024-01-24 03:57
"""
from uuid import uuid4
from django.db import migrations, models
class Migration(migrations.Migration):
    """
    Inquiry SQL table migration
    """
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name = 'Contact',
            options = {
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries',
            },
            fields = [(
                'id',
                models.UUIDField(
                    primary_key = True,
                    default = uuid4,
                    editable = False
                )
            ), (
                'listing_title',
                models.CharField()
            ), (
                'listing_id',
                models.IntegerField()
            ), (
                'first_name',
                models.CharField()
            ), (
                'last_name',
                models.CharField()
            ),  (
                'email_address',
                models.EmailField()
            ), (
                'phone_number',
                models.CharField()
            ), (
                'message',
                models.TextField(
                    blank = True
                )
            ), (
                'user_id',
                models.ForeignKey(
                    on_delete = models.DO_NOTHING,
                    to = 'auth.User',
                    blank = True
                )
            ), (
                'created_at',
                models.DateTimeField(
                    auto_now_add = True
                )
            ), (
                'updated_at',
                models.DateTimeField(
                    auto_now = True
                )
            )]
        )
    ]
