# Generated by Django 5.0.1 on 2024-01-08 03:32
from django.db.models.deletion import DO_NOTHING
from django.db import migrations, models
from cloudinary.models import CloudinaryField
from btre import UUIDAutoField
from btre.settings import CLOUDINARY_FOLDER
class Migration(migrations.Migration):
  initial = True
  dependencies = [(
    'realtors',
    '0001_initial'
  )]
  operations = [
    migrations.CreateModel(
      name = 'Listing',
      options = {
        'verbose_name': 'Listing',
        'verbose_name_plural': 'Listings',
        'db_table': 'listings',
      },
      fields = [(
        'id',
        UUIDAutoField(
          auto_created = True,
          primary_key = True,
          serialize = False,
          verbose_name = 'ID'
        )
      ), (
        'title',
        models.CharField()
      ), (
        'address',
        models.CharField()
      ), (
        'city',
        models.CharField()
      ), (
        'state',
        models.CharField()
      ), (
        'zipcode',
        models.CharField(
          max_length = 5
        )
      ), (
        'description',
        models.TextField(
          blank = True
        )
      ), (
        'price',
        models.DecimalField(
          decimal_places = 2,
          max_digits = 12
        )
      ), (
        'bedrooms',
        models.IntegerField()
      ), (
        'bathrooms',
        models.DecimalField(
          decimal_places = 1,
          max_digits = 2
        )
      ), (
        'garage',
          models.IntegerField(
            default = 0
          )
      ), (
        'sqft',
        models.DecimalField(
          decimal_places = 1,
          max_digits = 6
        )
      ), (
        'lot_size',
        models.DecimalField(
          decimal_places = 1,
          max_digits = 5
        )
      ), (
        'photo_main',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER
        )
      ), (
        'photo_1',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER,
          blank = True
        )
      ), (
        'photo_2',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER,
          blank = True
        )
      ), (
        'photo_3',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER,
          blank = True
        )
      ), (
        'photo_4',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER,
          blank = True
        )
      ), (
        'photo_5',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER,
          blank = True
        )
      ), (
        'photo_6',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER,
          blank = True
        )
      ), (
        'is_published',
        models.BooleanField(
          default = True
        )
      ), (
        'realtor_id',
        models.ForeignKey(
          on_delete = DO_NOTHING,
          to = 'realtors.realtor'
        )
      ), (
        'created_at',
        models.DateTimeField(
          auto_now_add = True
        )
      ), (
        'updated_at',
        models.DateTimeField(
          auto_now = True
        )
      )]
    )
  ]