# Generated by Django 5.0.1 on 2024-01-08 03:32

import datetime
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings
from cloudinary.models import CloudinaryField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zipcode', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.DecimalField(decimal_places=1, max_digits=6)),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', CloudinaryField('image', folder=settings.CLOUDINARY_FOLDER)),
                ('photo_1', CloudinaryField('image', folder=settings.CLOUDINARY_FOLDER, blank=True)),
                ('photo_2', CloudinaryField('image', folder=settings.CLOUDINARY_FOLDER, blank=True)),
                ('photo_3', CloudinaryField('image', folder=settings.CLOUDINARY_FOLDER, blank=True)),
                ('photo_4', CloudinaryField('image', folder=settings.CLOUDINARY_FOLDER, blank=True)),
                ('photo_5', CloudinaryField('image', folder=settings.CLOUDINARY_FOLDER, blank=True)),
                ('photo_6', CloudinaryField('image', folder=settings.CLOUDINARY_FOLDER, blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
