# Generated by Django 5.0.1 on 2024-01-08 03:32
from datetime import datetime
from django.db import migrations, models
from django.conf import settings
from cloudinary.models import CloudinaryField
class Migration(migrations.Migration):
  initial = True
  dependencies = []
  operations = [
    migrations.CreateModel(
      name='Realtor',
      fields=[(
        'id',
        models.BigAutoField(
          auto_created = True,
          primary_key = True,
          serialize = False,
          verbose_name = 'ID'
        )
      ), (
        'first',
        models.CharField()
      ), (
        'last',
        models.CharField()
      ), (
        'photo',
        CloudinaryField(
          'image',
          folder = settings.CLOUDINARY_FOLDER
        )
      ), (
        'description',
        models.TextField(
          blank = True
        )
      ), (
        'phone',
        models.CharField()
      ), (
        'email',
        models.CharField()
      ), (
        'is_mvp',
        models.BooleanField(
          default = False
        )
      ), (
        'hire_date',
        models.DateTimeField(
          blank = True,
          default = datetime.now
        )
      )]
    )
  ]