# Generated by Django 5.0.1 on 2024-01-08 03:32
from django.db import migrations, models
from cloudinary.models import CloudinaryField
from btre import UUIDAutoField
from btre.settings import CLOUDINARY_FOLDER
class Migration(migrations.Migration):
  initial = True
  dependencies = []
  operations = [
    migrations.CreateModel(
      name = 'Realtor',
      options = {
        'verbose_name': 'Realtor',
        'verbose_name_plural': 'Realtors',
        'db_table': 'realtors',
      },
      fields = [(
        'id',
        UUIDAutoField(
          auto_created = True,
          primary_key = True,
          serialize = False,
          verbose_name = 'ID'
        )
      ), (
        'first',
        models.CharField()
      ), (
        'last',
        models.CharField()
      ), (
        'photo',
        CloudinaryField(
          'image',
          folder = CLOUDINARY_FOLDER
        )
      ), (
        'description',
        models.TextField(
          blank = True
        )
      ), (
        'phone',
        models.CharField()
      ), (
        'email',
        models.CharField()
      ), (
        'is_mvp',
        models.BooleanField(
          default = False
        )
      ), (
        'created_at',
        models.DateTimeField(
          auto_now_add = True
        )
      ), (
        'updated_at',
        models.DateTimeField(
          auto_now = True
        )
      )]
    )
  ]